/* api request */
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

/* about negative list */
export const INIT_NEGATIVE_CANDIDATE = 'INIT_NEGATIVE_CANDIDATE';
export const GET_NEGATIVE_CANDIDATE_PENDING = 'GET_NEGATIVE_CANDIDATE_PENDING';
export const GET_NEGATIVE_CANDIDATE_SUCCESS = 'GET_NEGATIVE_CANDIDATE_SUCCESS';
export const GET_NEGATIVE_CANDIDATE_FAILURE = 'GET_NEGATIVE_CANDIDATE_FAILURE';

export const GET_NEGATIVE_CANDIDATE = 'GET_NEGATIVE_CANDIDATE';
